from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Callable

import pytest
import yaml

import tools.validate_step37_performance as validator


ROOT = Path(__file__).resolve().parents[2]
RECEIPT = Path(os.environ.get("STEP37_RECEIPT", str(ROOT / "output" / "step37_performance_validation.json"))).resolve()


def _payload() -> dict[str, Any]:
    if not RECEIPT.is_file():
        pytest.skip("Step37 evidence is generated by the bounded performance runner")
    return json.loads(RECEIPT.read_text(encoding="utf-8"))


def _closed_state(content_commit: str) -> dict[str, Any]:
    state = yaml.safe_load((ROOT / "docs/execution/MASTER_EXECUTION_STATE.yml").read_text(encoding="utf-8"))
    specialist = state["specialist_execution"]
    specialist.update(
        {
            "current_step": 38,
            "current_role": "load_stress",
            "current_specialist": "Step38 - Load / Stress Test Engineer",
            "last_completed_step": 37,
            "last_completed_role": "performance_engineer",
            "last_completed_specialist": "Step37 - Performance Engineer",
            "next_step": "Step38 - Load / Stress Test Engineer",
            "step38_started": False,
            "step38_status": "NOT_STARTED",
        }
    )
    for key in (
        "G12_CAPACITY",
        "G13_ADVERSARIAL_SECURITY",
        "G14_USABILITY",
        "G15_RELEASE",
    ):
        state["gates"][key] = "PENDING"
    specialist["last_completed_content_commit"] = content_commit
    receipt = specialist["step37_performance"]
    receipt.update({"content_commit": content_commit, "content_ci_head": content_commit, "content_ci_result": "PASS", "report_assessed_commit": content_commit, "status": "PASS", "step37_started": True})
    return state


def _assert_rejected(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mutate: Callable[[dict[str, Any], dict[str, Any]], None]) -> None:
    payload = _payload()
    assessed = payload["assessed_commit"]
    state = _closed_state(assessed)
    mutate(payload, state)
    evidence = tmp_path / "receipt.json"
    evidence.write_text(json.dumps(payload), encoding="utf-8")
    report = tmp_path / "report.md"
    report.write_text("step37 validator control", encoding="utf-8")
    monkeypatch.setattr(validator, "_state", lambda: state)
    monkeypatch.setattr(validator, "_head", lambda: assessed)
    with pytest.raises(SystemExit):
        validator.validate(evidence, report, assessed)


def test_step37_validator_accepts_real_e2e_medium_and_stage_receipts(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    payload = _payload()
    assessed = payload["assessed_commit"]
    state = _closed_state(assessed)
    evidence = tmp_path / "receipt.json"
    evidence.write_text(json.dumps(payload), encoding="utf-8")
    report = tmp_path / "report.md"
    report.write_text("step37 validator control", encoding="utf-8")
    monkeypatch.setattr(validator, "_state", lambda: state)
    monkeypatch.setattr(validator, "_head", lambda: assessed)
    assert validator.validate(evidence, report, assessed) == 0


@pytest.mark.parametrize(
    "mutate",
    (
        lambda p, s: next(item for item in p["benchmarks"] if item["benchmark_id"] == "PERF-E2E-001")["details"].update({"g6_status": "UNKNOWN"}),
        lambda p, s: p["large_scale_execution_status"].update({"Medium": "NOT_EXECUTED"}),
        lambda p, s: p["benchmarks"].remove(next(item for item in p["benchmarks"] if item["benchmark_id"] == "PERF-MEDIUM-001")),
        lambda p, s: p["medium_benchmark"]["details"].update({"row_count": 1024}),
        lambda p, s: p["provider_stage_baselines"]["dependency"].update({"status": "UNAVAILABLE"}),
        lambda p, s: (p["large_scale_execution_status"].update({"100M": "EXECUTED"}), p["large_scale_evidence"].update({"100M": {"status": "EXECUTED", "reason": "control"}})),
        lambda p, s: (p["upstream_gates"].update({"G12": "PASS"}), s["gates"].update({"G12_CAPACITY": "PASS"})),
        lambda p, s: (p["upstream_gates"].update({"step38_started": True}), s["specialist_execution"].update({"step38_started": True})),
    ),
)
def test_step37_validator_rejects_insufficient_or_premature_evidence(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mutate: Callable[[dict[str, Any], dict[str, Any]], None]) -> None:
    _assert_rejected(tmp_path, monkeypatch, mutate)
