from __future__ import annotations

import json
import os
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[2]
RECEIPT = Path(os.environ.get("STEP37_RECEIPT", str(ROOT / "output" / "step37_performance_validation.json"))).resolve()


def test_step37_receipt_is_truth_linked_and_not_a_stopwatch_unit_test() -> None:
    if not RECEIPT.is_file():
        pytest.skip("Step37 evidence is generated by the bounded performance runner")
    payload = json.loads(RECEIPT.read_text(encoding="utf-8"))
    assert payload["step"] == 37
    assert payload["truth_fixture_links"]
    assert all(item["path"].startswith("benchmarks/") for item in payload["truth_fixture_links"])
    assert payload["semantic_equivalence"]["status"] == "PASS"
    assert payload["upstream_gates"]["G12"] == "PENDING"
    assert payload["upstream_gates"]["step38_started"] is False


def test_step37_candidate_growth_records_status_for_optional_providers() -> None:
    if not RECEIPT.is_file():
        pytest.skip("Step37 evidence is generated by the bounded performance runner")
    payload = json.loads(RECEIPT.read_text(encoding="utf-8"))
    growth = payload["candidate_growth"]
    for key in ("dependency", "schema_matching", "entity_resolution"):
        assert growth[key]
        assert all("status" in row and "reason" in row for row in growth[key])


def test_step37_closure_receipt_contains_real_e2e_medium_and_provider_baselines() -> None:
    if not RECEIPT.is_file():
        pytest.skip("Step37 evidence is generated by the bounded performance runner")
    payload = json.loads(RECEIPT.read_text(encoding="utf-8"))
    benchmarks = {item["benchmark_id"]: item for item in payload["benchmarks"]}
    e2e = benchmarks["PERF-E2E-001"]
    assert e2e["status"] == "PASS"
    assert e2e["details"]["terminal_status"] == "SUCCEEDED"
    assert e2e["details"]["g6_status"] == "PASS"
    assert e2e["details"]["g6_eligible"] is True
    assert e2e["details"]["validated_output"] is True
    medium = benchmarks["PERF-MEDIUM-001"]
    assert medium["status"] == "PASS"
    assert medium["details"]["scale_class"] == "Medium"
    assert medium["details"]["row_count"] >= 100_000
    assert medium["details"]["semantic_oracle"]["status"] == "PASS"
    assert set(payload["provider_stage_baselines"]) == {"dependency", "schema_matching", "entity_resolution"}
    assert all(item["status"] == "PASS" for item in payload["provider_stage_baselines"].values())


def test_step37_does_not_claim_unexecuted_large_scales() -> None:
    if not RECEIPT.is_file():
        pytest.skip("Step37 evidence is generated by the bounded performance runner")
    status = json.loads(RECEIPT.read_text(encoding="utf-8"))["large_scale_execution_status"]
    assert status["1M"] == "NOT_EXECUTED"
    assert status["10M"] == "NOT_EXECUTED_OPTIONAL"
    assert status["100M"] == "FEASIBILITY_DESIGNED"
