/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Configuration */
        get: operations["product_configuration_api_v1_product_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Runs */
        get: operations["list_project_runs_api_v1_projects__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Artifact */
        post: operations["register_artifact_api_v1_runs__run_id__artifacts_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Content */
        get: operations["artifact_content_api_v1_runs__run_id__artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attempts */
        get: operations["list_attempts_api_v1_runs__run_id__attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempt */
        get: operations["get_attempt_api_v1_runs__run_id__attempts__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Execution */
        post: operations["cancel_execution_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Execution */
        post: operations["submit_execution_api_v1_runs__run_id__execution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/execution/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Execution Plan */
        post: operations["prepare_execution_plan_api_v1_runs__run_id__execution_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_runs__run_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Job */
        get: operations["get_run_job_api_v1_runs__run_id__jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/product-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Summary */
        get: operations["product_summary_api_v1_runs__run_id__product_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Execution */
        post: operations["resume_execution_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_runs__run_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reviews/{checkpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Review */
        post: operations["record_review_api_v1_runs__run_id__reviews__checkpoint__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reviews/{checkpoint}/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate Review */
        post: operations["invalidate_review_api_v1_runs__run_id__reviews__checkpoint__invalidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/source-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Product Source */
        post: operations["bind_product_source_api_v1_runs__run_id__source_selection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/validation/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation View */
        get: operations["validation_view_api_v1_runs__run_id__validation__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/visualizations/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visualization View */
        get: operations["visualization_view_api_v1_runs__run_id__visualizations__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Sources */
        get: operations["list_product_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Product Source */
        post: operations["import_product_source_api_v1_sources_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactView */
        ArtifactView: {
            /** Artifact Id */
            artifact_id: string;
            /** Artifact Kind */
            artifact_kind: string;
            /** Attempt Id */
            attempt_id: string;
            /** Byte Size */
            byte_size: number;
            /** Content Hash */
            content_hash: string;
            /** Logical Key */
            logical_key: string | null;
            /** Media Type */
            media_type: string;
            /** Producer */
            producer: string;
            /** Provenance Refs */
            provenance_refs: string[];
            /** Publication State */
            publication_state: string;
            /** Restricted */
            restricted: boolean;
            /** Retention Class */
            retention_class: string;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Stage Id */
            stage_id: string;
            /** Storage Mode */
            storage_mode: string;
        };
        /** BindSourceRequest */
        BindSourceRequest: {
            /**
             * Execution Context Id
             * @default step29-browser
             */
            execution_context_id: string;
            extraction?: components["schemas"]["ExtractionPolicy"];
            /** Registry Id */
            registry_id: string;
            scope?: components["schemas"]["SelectionScope"];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Git Content Commit */
            git_content_commit?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
            /** Project Id */
            project_id: string;
        };
        /**
         * DeliveryPhase
         * @description Durable delivery markers surrounding an external stage handler call.
         * @enum {string}
         */
        DeliveryPhase: "NOT_STARTED" | "ATTEMPT_CREATED" | "HANDLER_DELIVERY_STARTED" | "RESULT_RECORDED" | "FINALIZED" | "RECONCILIATION_REQUIRED";
        /**
         * ExecutionPlanIntent
         * @description Bounded caller intent; it contains no selection authority.
         */
        ExecutionPlanIntent: {
            /** Cross Source Mapping Requested */
            cross_source_mapping_requested?: boolean | null;
            /** Entity Resolution Requested */
            entity_resolution_requested?: boolean | null;
            /**
             * Learned Evidence Enabled
             * @default false
             */
            learned_evidence_enabled: boolean;
            /**
             * Optional Semantic Evidence Enabled
             * @default false
             */
            optional_semantic_evidence_enabled: boolean;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /** ExtractionPolicy */
        ExtractionPolicy: {
            /** Chunk Size */
            chunk_size: number;
            /** Max Rows */
            max_rows?: number | null;
            /** @default SOURCE_WIDE */
            max_rows_scope: components["schemas"]["MaxRowsScope"];
            /**
             * Null Markers
             * @default []
             */
            null_markers: string[];
            /**
             * Preserve Raw Values
             * @default true
             */
            preserve_raw_values: boolean;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * FailureClassification
         * @enum {string}
         */
        FailureClassification: "RETRYABLE_TRANSIENT" | "TERMINAL_FAILURE" | "BLOCKED_PREREQUISITE" | "NEEDS_REVIEW" | "CANCELLED" | "UNKNOWN_SIDE_EFFECT";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvalidateReviewRequest */
        InvalidateReviewRequest: {
            context?: components["schemas"]["ReviewCompatibilityContext"] | null;
            /** Expected Revision */
            expected_revision: number;
            /** Reason */
            reason: string;
            /** Subject Artifact Id */
            subject_artifact_id?: string | null;
            /** Subject Content Hash */
            subject_content_hash?: string | null;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "COMMAND" | "STAGE";
        /**
         * JobRecord
         * @description Safe durable job projection suitable for Step29 read/query consumers.
         */
        JobRecord: {
            /** Action */
            action?: string | null;
            /** Attempt Id */
            attempt_id?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at?: string;
            /**
             * Cancellation Requested
             * @default false
             */
            cancellation_requested: boolean;
            /** Cancellation Requested At */
            cancellation_requested_at?: string | null;
            /** Command Id */
            command_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Delivery Count
             * @default 0
             */
            delivery_count: number;
            /** @default NOT_STARTED */
            delivery_phase: components["schemas"]["DeliveryPhase"];
            /** Durable Result */
            durable_result?: {
                [key: string]: unknown;
            } | null;
            failure_classification?: components["schemas"]["FailureClassification"] | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Job Id */
            job_id: string;
            job_kind: components["schemas"]["JobKind"];
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /**
             * Lease Generation
             * @default 0
             */
            lease_generation: number;
            /** Lease Owner */
            lease_owner?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
            /** Parent Job Id */
            parent_job_id?: string | null;
            /** Plan Id */
            plan_id?: string | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** @default RECONCILIATION_REQUIRED_ON_UNKNOWN */
            replay_safety: components["schemas"]["ReplaySafety"];
            /**
             * Result Refs
             * @default []
             */
            result_refs: string[];
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            review_context?: components["schemas"]["ReviewCompatibilityContext"] | null;
            /**
             * Review Contexts
             * @default []
             */
            review_contexts: components["schemas"]["ReviewCompatibilityContext"][];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Source Scope */
            source_scope?: string | null;
            /** Stage Id */
            stage_id?: string | null;
            /** @default QUEUED */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "QUEUED" | "RUNNING" | "RETRY_WAIT" | "NEEDS_REVIEW" | "BLOCKED" | "FAILED" | "CANCELLED" | "SUCCEEDED";
        /**
         * MaxRowsScope
         * @enum {string}
         */
        MaxRowsScope: "SOURCE_WIDE" | "PER_TABLE";
        /** PageResponse */
        PageResponse: {
            /** Items */
            items: unknown[];
            /** Next Offset */
            next_offset: number | null;
            /** Offset */
            offset: number;
            /** Order By */
            order_by: string;
            /** Page Size */
            page_size: number;
        };
        /** PrepareExecutionPlanRequest */
        PrepareExecutionPlanRequest: {
            intent: components["schemas"]["ExecutionPlanIntent"];
        };
        /** ProductAnalyticalView */
        ProductAnalyticalView: {
            /**
             * Dimension Ids
             * @default []
             */
            dimension_ids: string[];
            /**
             * Fact Ids
             * @default []
             */
            fact_ids: string[];
            /**
             * Grain Ids
             * @default []
             */
            grain_ids: string[];
            /**
             * Measure Ids
             * @default []
             */
            measure_ids: string[];
            /**
             * Measure Semantics
             * @default []
             */
            measure_semantics: string[];
            /** Plan Id */
            plan_id?: string | null;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * State
             * @default NOT_EVALUATED
             */
            state: string;
        };
        /** ProductCanonicalView */
        ProductCanonicalView: {
            /**
             * Entity Type Ids
             * @default []
             */
            entity_type_ids: string[];
            /** Hypothesis Id */
            hypothesis_id?: string | null;
            /**
             * Identity Basis
             * @default []
             */
            identity_basis: string[];
            /**
             * Membership Count
             * @default 0
             */
            membership_count: number;
            /** Model Id */
            model_id?: string | null;
            /** Proposal Id */
            proposal_id?: string | null;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * State
             * @default NOT_EVALUATED
             */
            state: string;
        };
        /** ProductConfiguration */
        ProductConfiguration: {
            /**
             * Authentication Mode
             * @default local_test_reference_only
             */
            authentication_mode: string;
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /** ProductDataConditionView */
        ProductDataConditionView: {
            /**
             * Column Count
             * @default 0
             */
            column_count: number;
            /**
             * Null Columns
             * @default []
             */
            null_columns: string[];
            /**
             * Observation Scope
             * @default unknown
             */
            observation_scope: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Source Rows Observed
             * @default 0
             */
            source_rows_observed: number;
            /**
             * Staged Rows
             * @default 0
             */
            staged_rows: number;
            /**
             * State
             * @default NOT_EVALUATED
             */
            state: string;
        };
        /** ProductMaterializationView */
        ProductMaterializationView: {
            /** Artifact Id */
            artifact_id?: string | null;
            /** Row Counts */
            row_counts?: {
                [key: string]: number;
            };
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Status
             * @default NOT_EVALUATED
             */
            status: string;
            /**
             * Table Names
             * @default []
             */
            table_names: string[];
            /** Target Type */
            target_type?: string | null;
            /**
             * Usable
             * @default false
             */
            usable: boolean;
        };
        /** ProductOutputView */
        ProductOutputView: {
            /** Materialization Artifact Id */
            materialization_artifact_id?: string | null;
            /** Row Counts */
            row_counts?: {
                [key: string]: number;
            };
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Table Names
             * @default []
             */
            table_names: string[];
            /**
             * Validated
             * @default false
             */
            validated: boolean;
        };
        /** ProductRelationshipView */
        ProductRelationshipView: {
            /** Confidence Band */
            confidence_band: string;
            /** Decision Id */
            decision_id: string;
            /** Decision State */
            decision_state: string;
            /** From Columns */
            from_columns: string[];
            /** From Table */
            from_table: string;
            /**
             * Missing Evidence Count
             * @default 0
             */
            missing_evidence_count: number;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Score Semantics */
            score_semantics: string;
            /** Score Value */
            score_value?: number | null;
            /** Subject Id */
            subject_id: string;
            /**
             * Supporting Signal Count
             * @default 0
             */
            supporting_signal_count: number;
            /** To Columns */
            to_columns: string[];
            /** To Table */
            to_table: string;
        };
        /** ProductReviewView */
        ProductReviewView: {
            /** Checkpoint */
            checkpoint: string;
            context: components["schemas"]["ReviewCompatibilityContext"];
            /** Decision */
            decision?: string | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** State */
            state: string;
            /** Subject Artifact Id */
            subject_artifact_id: string;
            /** Subject Content Hash */
            subject_content_hash: string;
            /** Subject Semantic Id */
            subject_semantic_id: string;
        };
        /** ProductSourceBinding */
        ProductSourceBinding: {
            /** Extraction Chunk Size */
            extraction_chunk_size: number;
            /** Extraction Max Rows */
            extraction_max_rows?: number | null;
            /** Registry Id */
            registry_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Selection Artifact Id */
            selection_artifact_id: string;
            /** Source Display Name */
            source_display_name: string;
            /** Source Id */
            source_id?: string | null;
        };
        /** ProductSourceView */
        ProductSourceView: {
            /** Adapter Name */
            adapter_name: string;
            /** Display Name */
            display_name: string;
            /**
             * Read Only
             * @default true
             */
            read_only: boolean;
            /** Registry Id */
            registry_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Source Id */
            source_id?: string | null;
            /** Source Type */
            source_type: string;
        };
        /** ProductStageView */
        ProductStageView: {
            /**
             * Artifact Ids
             * @default []
             */
            artifact_ids: string[];
            /**
             * Artifact Kinds
             * @default []
             */
            artifact_kinds: string[];
            /** Required */
            required: boolean;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Selected */
            selected: boolean;
            /** Stage Id */
            stage_id: string;
            /** Status */
            status: string;
        };
        /** ProductSummary */
        ProductSummary: {
            analytical: components["schemas"]["ProductAnalyticalView"];
            canonical: components["schemas"]["ProductCanonicalView"];
            /** Current Stage */
            current_stage?: string | null;
            data_condition: components["schemas"]["ProductDataConditionView"];
            materialization: components["schemas"]["ProductMaterializationView"];
            output: components["schemas"]["ProductOutputView"];
            /**
             * Pending Reviews
             * @default []
             */
            pending_reviews: components["schemas"]["ProductReviewView"][];
            /** Planning Phase */
            planning_phase?: string | null;
            /**
             * Privacy Note
             * @default Raw rows, file paths, SQL and credentials are not exposed by this product boundary.
             */
            privacy_note: string;
            /** Project Id */
            project_id: string;
            /**
             * Relationships
             * @default []
             */
            relationships: components["schemas"]["ProductRelationshipView"][];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            source?: components["schemas"]["ProductSourceView"] | null;
            source_binding?: components["schemas"]["ProductSourceBinding"] | null;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["ProductStageView"][];
            /** Status */
            status: string;
            validation: components["schemas"]["ProductValidationView"];
        };
        /** ProductValidationView */
        ProductValidationView: {
            /**
             * Failed Check Count
             * @default 0
             */
            failed_check_count: number;
            /**
             * G6 Eligible
             * @default false
             */
            g6_eligible: boolean;
            /**
             * G6 Status
             * @default PENDING
             */
            g6_status: string;
            /**
             * Not Evaluated Check Count
             * @default 0
             */
            not_evaluated_check_count: number;
            /**
             * Overall Status
             * @default NOT_EVALUATED
             */
            overall_status: string;
            /**
             * Passed Check Count
             * @default 0
             */
            passed_check_count: number;
            /** Report Id */
            report_id?: string | null;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Validation Artifact Id */
            validation_artifact_id?: string | null;
        };
        /** RegisterArtifactRequest */
        RegisterArtifactRequest: {
            /** Artifact Id */
            artifact_id: string;
        };
        /**
         * ReplaySafety
         * @description The durable contract used when a handler delivery outcome is unknown.
         * @enum {string}
         */
        ReplaySafety: "REPLAY_SAFE" | "RECONCILIATION_REQUIRED_ON_UNKNOWN";
        /**
         * ReviewActionDecision
         * @description Step27 actions; SKIPPED is not exposed without server authorization.
         * @enum {string}
         */
        ReviewActionDecision: "ACCEPTED" | "REJECTED" | "DEFERRED";
        /** ReviewActionRequest */
        ReviewActionRequest: {
            context?: components["schemas"]["ReviewCompatibilityContext"] | null;
            decision: components["schemas"]["ReviewActionDecision"];
            /**
             * Expected Revision
             * @default 0
             */
            expected_revision: number;
            /** Rationale */
            rationale: string;
            /** Subject Artifact Id */
            subject_artifact_id?: string | null;
            /** Subject Content Hash */
            subject_content_hash?: string | null;
        };
        /**
         * ReviewCheckpoint
         * @enum {string}
         */
        ReviewCheckpoint: "REVIEW_EVIDENCE_DECISIONS" | "REVIEW_CANONICAL_IDENTITY" | "REVIEW_ANALYTICAL_PLAN" | "REVIEW_MATERIALIZATION_PLAN";
        /** ReviewCompatibilityContext */
        ReviewCompatibilityContext: {
            /** Applicability Fingerprint */
            applicability_fingerprint: string;
            /**
             * Domain Assertion Refs
             * @default []
             */
            domain_assertion_refs: string[];
            /** Model Version */
            model_version: string;
            /** Policy Version */
            policy_version: string;
            review_checkpoint_id: components["schemas"]["ReviewCheckpoint"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            skip_authorization?: components["schemas"]["ReviewSkipAuthorization"] | null;
            /** Source Schema Fingerprints */
            source_schema_fingerprints?: {
                [key: string]: string;
            };
            /** Subject Artifact Id */
            subject_artifact_id: string;
            /** Subject Content Hash */
            subject_content_hash: string;
            /** Subject Schema Version */
            subject_schema_version: string;
            /** Subject Semantic Id */
            subject_semantic_id: string;
            /** Subject Stage */
            subject_stage: string;
        };
        /** ReviewSkipAuthorization */
        ReviewSkipAuthorization: {
            /** Applicability Fingerprint */
            applicability_fingerprint: string;
            checkpoint: components["schemas"]["ReviewCheckpoint"];
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: string;
            /** Reason */
            reason: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Scope */
            scope: string;
        };
        /**
         * RunView
         * @description Safe run projection; internal metadata is intentionally omitted.
         */
        RunView: {
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Created At */
            created_at: string;
            /** Gate Refs */
            gate_refs: string[];
            /** Git Content Commit */
            git_content_commit: string | null;
            /** Latest Stage Refs */
            latest_stage_refs: {
                [key: string]: string;
            };
            /** Project Id */
            project_id: string;
            /** Revision */
            revision: number;
            /** Root Artifact Refs */
            root_artifact_refs: string[];
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Source Snapshot Refs */
            source_snapshot_refs: string[];
            /** Status */
            status: string;
        };
        /** SelectionScope */
        SelectionScope: {
            /**
             * Excluded Objects
             * @default []
             */
            excluded_objects: string[];
            /**
             * Include Views
             * @default false
             */
            include_views: boolean;
            /** Included Columns */
            included_columns?: {
                [key: string]: string[];
            };
            /**
             * Included Objects
             * @default []
             */
            included_objects: string[];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /** StageAttemptRecord */
        StageAttemptRecord: {
            /** Attempt Id */
            attempt_id: string;
            /** Attempt Number */
            attempt_number: number;
            /**
             * Delivery Phase
             * @default ATTEMPT_CREATED
             */
            delivery_phase: string;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Input Artifact Refs
             * @default []
             */
            input_artifact_refs: string[];
            /**
             * Output Artifact Refs
             * @default []
             */
            output_artifact_refs: string[];
            /** Policy Config Fingerprint */
            policy_config_fingerprint: string;
            /** Resource Budget Ref */
            resource_budget_ref?: string | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Stage Id */
            stage_id: string;
            /** Started At */
            started_at?: string | null;
            /** @default PENDING */
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "NEEDS_REVIEW" | "BLOCKED" | "FAILED" | "CANCELLED" | "INVALIDATED" | "SKIPPED";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_configuration_api_v1_product_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductConfiguration"];
                };
            };
        };
    };
    list_project_runs_api_v1_projects__project_id__runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: {
                stage_id?: string | null;
                artifact_kind?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_artifact_api_v1_runs__run_id__artifacts_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterArtifactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_content_api_v1_runs__run_id__artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attempts_api_v1_runs__run_id__attempts_get: {
        parameters: {
            query?: {
                stage_id?: string | null;
                status?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_api_v1_runs__run_id__attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageAttemptRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_execution_api_v1_runs__run_id__execution_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_execution_plan_api_v1_runs__run_id__execution_prepare_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareExecutionPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_runs__run_id__jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_job_api_v1_runs__run_id__jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_summary_api_v1_runs__run_id__product_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_execution_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_runs__run_id__reviews_get: {
        parameters: {
            query?: {
                subject_key?: string | null;
                page_size?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_review_api_v1_runs__run_id__reviews__checkpoint__post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                checkpoint: components["schemas"]["ReviewCheckpoint"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invalidate_review_api_v1_runs__run_id__reviews__checkpoint__invalidate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                checkpoint: components["schemas"]["ReviewCheckpoint"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvalidateReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_product_source_api_v1_runs__run_id__source_selection_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSourceBinding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_view_api_v1_runs__run_id__validation__artifact_id__get: {
        parameters: {
            query?: {
                visualization_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visualization_view_api_v1_runs__run_id__visualizations__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSourceView"][];
                };
            };
        };
    };
    import_product_source_api_v1_sources_import_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Source-Filename"?: string;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSourceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
